# Generated by Django 4.0.4 on 2022-05-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_on',
        ),
    ]
